# Generated by Django 2.0 on 2021-09-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
