# Generated by Django 3.2.6 on 2021-09-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='midroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_person', models.CharField(max_length=256)),
                ('theroom', models.CharField(max_length=50)),
            ],
        ),
    ]
